### ISSUE TITLE
depth map

### ISSUE THREAD

**Issue by qlfwake** [Hans1984/TAF#1]
Hello, I have studied your article and am very interested in it, but I found that the test code only generates five images without depth map, may I ask if there is something wrong with my operation

**Comment by Hans1984** [comment]
hi, thanks for our attention, the depth map is calculated in https://github.com/Hans1984/TAF/blob/main/train.py#L43, you can  convey the tensor to numpy and save it.

**Comment by qlfwake** [comment]
Glad to receive your letter,
I studied your test code and found that there was no image data in the input, so I directly input the trained weights. According to my study of your paper, I think the process should be to input image stack, output depth map and full-focus high dynamic range image, but this process is not the case in test, may I ask if my understanding is wrong?
I'm sorry to bother you again

**Comment by Hans1984** [comment]
Hi, 

The inputs are coordinates, use the TAF model (MLPs) to render images, you can check this paper for further understanding, how to use the MLP to represent signals, https://www.vincentsitzmann.com/siren/ 
:)
Best.

**Comment by qlfwake** [comment]
Thank you for your help. I'll study it again. Maybe I haven't understood it yet

**Comment by Hans1984** [comment]
You'r welcome :)

**Comment by qlfwake** [comment]
I'm sorry to bother you again.
After reading your paper again, it is still my understanding that the purpose is to learn the corresponding depth map and AiF HDR image from the input stack of images with different defocusing distances, but this does not seem to be reflected in your "test" code, which only generates five images with different focal lengths, apertures and exposures.
Is my understanding wrong? The pre-training weights you provided were in test, why not the input image stack?

**Comment by Hans1984** [comment]
Ok, first the inputs are [-1, 1] ccordinates, which will be taken into the MLPs. The MLPs will render the RGB images which will be comapred with the TAF stack, and optimise the MLPs. After such training, the MLPs can represent the TAF satck and do editing. So in the inference stage, just take the coordinates and then it can generate the RGB images and depth. You can check this line https://github.com/Hans1984/TAF/blob/main/test.py#L79 to save the depth map.

Hope such explaination can solve your conerns, bty, highly suggest to read the SIREN paper.

**Comment by qlfwake** [comment]
Well, thank you for your reply. I'll try to understand again
